import type { Metadata } from "next";
import { Bebas_Neue, Rubik } from "next/font/google";
import "./../globals.css";
import Header from "@/components/custom/header/Header";
import Footer from "@/components/custom/Footer";

import { FavouriteContextProvider } from "@/context/favourite-context";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "sonner";
import { CartContextProvider } from "@/context/cart-context";


const bebas = Bebas_Neue({
  variable: "--font-bebas",
  subsets: ["latin"],
  weight: ['400']
});

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
  weight: ['300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bebas.variable} ${rubik.variable} antialiased `}
      >
        <SessionProvider>
          <CartContextProvider>

            <FavouriteContextProvider>
              <Header />
              <Toaster />
              {children}
              <Footer />
            </FavouriteContextProvider>
          </CartContextProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
